name: Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version to release (e.g., 1.0.1)'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          
      - name: Install dependencies
        run: npm ci
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
      - name: Set version
        id: set_version
        run: |
          # Directly set the version from input
          npm version ${{ github.event.inputs.release_version }} --no-git-tag-version --allow-same-version
          
          # Store the version for later use
          echo "new_version=${{ github.event.inputs.release_version }}" >> $GITHUB_OUTPUT
          
      - name: Commit changes
        run: |
          git add package.json package-lock.json
          git commit -m "chore: set version to ${{ steps.set_version.outputs.new_version }}"
          git push
          
      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.set_version.outputs.new_version }}
          release_name: Release v${{ steps.set_version.outputs.new_version }}
          draft: false
          prerelease: false
